// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A Duration represents a signed, fixed-length span of time represented
 * as a count of seconds and fractions of seconds at nanosecond
 * resolution. It is independent of any calendar and concepts like "day"
 * or "month". It is related to Timestamp in that the difference between
 * two Timestamp values is a Duration and it can be added or subtracted
 * from a Timestamp. Range is approximately +-10,000 years.
 *
 * Based on google protobuf duration definition: <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/duration.proto>
 */
export class Duration implements flatbuffers.IUnpackableObject<DurationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Duration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Signed seconds of the span of time. Must be from -315,576,000,000
 * to +315,576,000,000 inclusive. Note: these bounds are computed from:
 * 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
 */
seconds():bigint {
  return this.bb!.readInt64(this.bb_pos);
}

/**
 * Signed fractions of a second at nanosecond resolution of the span
 * of time. Durations less than one second are represented with a 0
 * `seconds` field and a positive or negative `nanos` field. For durations
 * of one second or more, a non-zero value for the `nanos` field must be
 * of the same sign as the `seconds` field. Must be from -999,999,999
 * to +999,999,999 inclusive.
 */
nanos():number {
  return this.bb!.readInt32(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createDuration(builder:flatbuffers.Builder, seconds: bigint, nanos: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.pad(4);
  builder.writeInt32(nanos);
  builder.writeInt64(BigInt(seconds ?? 0));
  return builder.offset();
}


unpack(): DurationT {
  return new DurationT(
    this.seconds(),
    this.nanos()
  );
}


unpackTo(_o: DurationT): void {
  _o.seconds = this.seconds();
  _o.nanos = this.nanos();
}
}

export class DurationT implements flatbuffers.IGeneratedObject {
constructor(
  public seconds: bigint = BigInt('0'),
  public nanos: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Duration.createDuration(builder,
    this.seconds,
    this.nanos
  );
}
}
