// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * The state of the provider definition. The state will be set by the registry.
 */
export enum ProviderDefinitionState {
  /**
   * The state is unspecified.
   */
  UNSPECIFIED = 0,

  /**
   * The provider definition is ok and valid.
   */
  OK = 1,

  /**
   * The provider definition is invalid => variable_definitions.size = 0
   */
  INVALID = 2
}
