// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Provider, ProviderT } from '../../../weidmueller/ucontrol/hub/provider.js';


/**
 * A list of providers that provide variables to consumers.
 */
export class ProviderList implements flatbuffers.IUnpackableObject<ProviderListT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProviderList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProviderList(bb:flatbuffers.ByteBuffer, obj?:ProviderList):ProviderList {
  return (obj || new ProviderList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProviderList(bb:flatbuffers.ByteBuffer, obj?:ProviderList):ProviderList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProviderList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The list of providers.
 */
items(index: number, obj?:Provider):Provider|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Provider()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startProviderList(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endProviderList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProviderList(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProviderList.startProviderList(builder);
  ProviderList.addItems(builder, itemsOffset);
  return ProviderList.endProviderList(builder);
}

unpack(): ProviderListT {
  return new ProviderListT(
    this.bb!.createObjList<Provider, ProviderT>(this.items.bind(this), this.itemsLength())
  );
}


unpackTo(_o: ProviderListT): void {
  _o.items = this.bb!.createObjList<Provider, ProviderT>(this.items.bind(this), this.itemsLength());
}
}

export class ProviderListT implements flatbuffers.IGeneratedObject {
constructor(
  public items: (ProviderT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const items = ProviderList.createItemsVector(builder, builder.createObjectOffsetList(this.items));

  return ProviderList.createProviderList(builder,
    items
  );
}
}
