// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProviderDefinition, ProviderDefinitionT } from '../../../weidmueller/ucontrol/hub/provider-definition.js';


/**
 * An event that describes a provider's definition that has just changed.
 */
export class ProviderDefinitionChangedEvent implements flatbuffers.IUnpackableObject<ProviderDefinitionChangedEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProviderDefinitionChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProviderDefinitionChangedEvent(bb:flatbuffers.ByteBuffer, obj?:ProviderDefinitionChangedEvent):ProviderDefinitionChangedEvent {
  return (obj || new ProviderDefinitionChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProviderDefinitionChangedEvent(bb:flatbuffers.ByteBuffer, obj?:ProviderDefinitionChangedEvent):ProviderDefinitionChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProviderDefinitionChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A definition that has just been changed.
 * If the provider_definition is null, the provider is removed.
 */
providerDefinition(obj?:ProviderDefinition):ProviderDefinition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ProviderDefinition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startProviderDefinitionChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProviderDefinition(builder:flatbuffers.Builder, providerDefinitionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, providerDefinitionOffset, 0);
}

static endProviderDefinitionChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishProviderDefinitionChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedProviderDefinitionChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createProviderDefinitionChangedEvent(builder:flatbuffers.Builder, providerDefinitionOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProviderDefinitionChangedEvent.startProviderDefinitionChangedEvent(builder);
  ProviderDefinitionChangedEvent.addProviderDefinition(builder, providerDefinitionOffset);
  return ProviderDefinitionChangedEvent.endProviderDefinitionChangedEvent(builder);
}

unpack(): ProviderDefinitionChangedEventT {
  return new ProviderDefinitionChangedEventT(
    (this.providerDefinition() !== null ? this.providerDefinition()!.unpack() : null)
  );
}


unpackTo(_o: ProviderDefinitionChangedEventT): void {
  _o.providerDefinition = (this.providerDefinition() !== null ? this.providerDefinition()!.unpack() : null);
}
}

export class ProviderDefinitionChangedEventT implements flatbuffers.IGeneratedObject {
constructor(
  public providerDefinition: ProviderDefinitionT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const providerDefinition = (this.providerDefinition !== null ? this.providerDefinition!.pack(builder) : 0);

  return ProviderDefinitionChangedEvent.createProviderDefinitionChangedEvent(builder,
    providerDefinition
  );
}
}
