// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProviderDefinitionState } from '../../../weidmueller/ucontrol/hub/provider-definition-state.js';
import { VariableDefinition, VariableDefinitionT } from '../../../weidmueller/ucontrol/hub/variable-definition.js';


/**
 * A definition of a provider's provided variables.
 *
 * Definition elements have a flat list instead of a hierarchy structure.
 * They support the folder concept as a means of grouping definitions by using
 * a shared key prefix for the grouped definitions.
 * This means that the grouped definitions have keys that begin with a common
 * string.
 * This common string, or shared prefix, is the folder key.
 *
 * For security reasons, the provider id must be extracted from the
 * communication channel.
 */
export class ProviderDefinition implements flatbuffers.IUnpackableObject<ProviderDefinitionT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProviderDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProviderDefinition(bb:flatbuffers.ByteBuffer, obj?:ProviderDefinition):ProviderDefinition {
  return (obj || new ProviderDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProviderDefinition(bb:flatbuffers.ByteBuffer, obj?:ProviderDefinition):ProviderDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProviderDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The fingerprint is a version identification of the provider definition.
 *
 * Therefore, the fingerprint can be used by a consumer to check whether
 * the provider's definition matches the values received.
 * Whenever a provider definition changed, the provider must change the
 * fingerprint.
 */
fingerprint():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * The list of variable definitions.
 */
variableDefinitions(index: number, obj?:VariableDefinition):VariableDefinition|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new VariableDefinition()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

variableDefinitionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * The current state of the provider definition. The state will be set by the registry.
 */
state():ProviderDefinitionState {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ProviderDefinitionState.UNSPECIFIED;
}

static startProviderDefinition(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addFingerprint(builder:flatbuffers.Builder, fingerprint:bigint) {
  builder.addFieldInt64(0, fingerprint, BigInt('0'));
}

static addVariableDefinitions(builder:flatbuffers.Builder, variableDefinitionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, variableDefinitionsOffset, 0);
}

static createVariableDefinitionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVariableDefinitionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addState(builder:flatbuffers.Builder, state:ProviderDefinitionState) {
  builder.addFieldInt8(2, state, ProviderDefinitionState.UNSPECIFIED);
}

static endProviderDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createProviderDefinition(builder:flatbuffers.Builder, fingerprint:bigint, variableDefinitionsOffset:flatbuffers.Offset, state:ProviderDefinitionState):flatbuffers.Offset {
  ProviderDefinition.startProviderDefinition(builder);
  ProviderDefinition.addFingerprint(builder, fingerprint);
  ProviderDefinition.addVariableDefinitions(builder, variableDefinitionsOffset);
  ProviderDefinition.addState(builder, state);
  return ProviderDefinition.endProviderDefinition(builder);
}

unpack(): ProviderDefinitionT {
  return new ProviderDefinitionT(
    this.fingerprint(),
    this.bb!.createObjList<VariableDefinition, VariableDefinitionT>(this.variableDefinitions.bind(this), this.variableDefinitionsLength()),
    this.state()
  );
}


unpackTo(_o: ProviderDefinitionT): void {
  _o.fingerprint = this.fingerprint();
  _o.variableDefinitions = this.bb!.createObjList<VariableDefinition, VariableDefinitionT>(this.variableDefinitions.bind(this), this.variableDefinitionsLength());
  _o.state = this.state();
}
}

export class ProviderDefinitionT implements flatbuffers.IGeneratedObject {
constructor(
  public fingerprint: bigint = BigInt('0'),
  public variableDefinitions: (VariableDefinitionT)[] = [],
  public state: ProviderDefinitionState = ProviderDefinitionState.UNSPECIFIED
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const variableDefinitions = ProviderDefinition.createVariableDefinitionsVector(builder, builder.createObjectOffsetList(this.variableDefinitions));

  return ProviderDefinition.createProviderDefinition(builder,
    this.fingerprint,
    variableDefinitions,
    this.state
  );
}
}
