// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A provider that provides variables to consumers.
 */
export class Provider implements flatbuffers.IUnpackableObject<ProviderT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Provider {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProvider(bb:flatbuffers.ByteBuffer, obj?:Provider):Provider {
  return (obj || new Provider()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProvider(bb:flatbuffers.ByteBuffer, obj?:Provider):Provider {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Provider()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The id of the provider.
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startProvider(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static endProvider(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

static createProvider(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  Provider.startProvider(builder);
  Provider.addId(builder, idOffset);
  return Provider.endProvider(builder);
}

unpack(): ProviderT {
  return new ProviderT(
    this.id()
  );
}


unpackTo(_o: ProviderT): void {
  _o.id = this.id();
}
}

export class ProviderT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);

  return Provider.createProvider(builder,
    id
  );
}
}
