// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProviderList, ProviderListT } from '../../../weidmueller/ucontrol/hub/provider-list.js';


/**
 * An event that describes a list of providers that have just changed.
 */
export class ProvidersChangedEvent implements flatbuffers.IUnpackableObject<ProvidersChangedEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ProvidersChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsProvidersChangedEvent(bb:flatbuffers.ByteBuffer, obj?:ProvidersChangedEvent):ProvidersChangedEvent {
  return (obj || new ProvidersChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsProvidersChangedEvent(bb:flatbuffers.ByteBuffer, obj?:ProvidersChangedEvent):ProvidersChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ProvidersChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of providers that have just been changed.
 */
providers(obj?:ProviderList):ProviderList|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ProviderList()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startProvidersChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProviders(builder:flatbuffers.Builder, providersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, providersOffset, 0);
}

static endProvidersChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // providers
  return offset;
}

static finishProvidersChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedProvidersChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createProvidersChangedEvent(builder:flatbuffers.Builder, providersOffset:flatbuffers.Offset):flatbuffers.Offset {
  ProvidersChangedEvent.startProvidersChangedEvent(builder);
  ProvidersChangedEvent.addProviders(builder, providersOffset);
  return ProvidersChangedEvent.endProvidersChangedEvent(builder);
}

unpack(): ProvidersChangedEventT {
  return new ProvidersChangedEventT(
    (this.providers() !== null ? this.providers()!.unpack() : null)
  );
}


unpackTo(_o: ProvidersChangedEventT): void {
  _o.providers = (this.providers() !== null ? this.providers()!.unpack() : null);
}
}

export class ProvidersChangedEventT implements flatbuffers.IGeneratedObject {
constructor(
  public providers: ProviderListT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const providers = (this.providers !== null ? this.providers!.pack(builder) : 0);

  return ProvidersChangedEvent.createProvidersChangedEvent(builder,
    providers
  );
}
}
