// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { VariableList, VariableListT } from '../../../weidmueller/ucontrol/hub/variable-list.js';


/**
 * A query response that responds to a requested list of provider variables.
 */
export class ReadVariablesQueryResponse implements flatbuffers.IUnpackableObject<ReadVariablesQueryResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadVariablesQueryResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadVariablesQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadVariablesQueryResponse):ReadVariablesQueryResponse {
  return (obj || new ReadVariablesQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadVariablesQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadVariablesQueryResponse):ReadVariablesQueryResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadVariablesQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of variables that have been requested.
 */
variables(obj?:VariableList):VariableList|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VariableList()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startReadVariablesQueryResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addVariables(builder:flatbuffers.Builder, variablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, variablesOffset, 0);
}

static endReadVariablesQueryResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // variables
  return offset;
}

static finishReadVariablesQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadVariablesQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadVariablesQueryResponse(builder:flatbuffers.Builder, variablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReadVariablesQueryResponse.startReadVariablesQueryResponse(builder);
  ReadVariablesQueryResponse.addVariables(builder, variablesOffset);
  return ReadVariablesQueryResponse.endReadVariablesQueryResponse(builder);
}

unpack(): ReadVariablesQueryResponseT {
  return new ReadVariablesQueryResponseT(
    (this.variables() !== null ? this.variables()!.unpack() : null)
  );
}


unpackTo(_o: ReadVariablesQueryResponseT): void {
  _o.variables = (this.variables() !== null ? this.variables()!.unpack() : null);
}
}

export class ReadVariablesQueryResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public variables: VariableListT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const variables = (this.variables !== null ? this.variables!.pack(builder) : 0);

  return ReadVariablesQueryResponse.createReadVariablesQueryResponse(builder,
    variables
  );
}
}
