// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A query that requests a list of variables from a single provider.
 *
 * The returned variables can be filtered using an array of IDs.
 */
export class ReadVariablesQueryRequest implements flatbuffers.IUnpackableObject<ReadVariablesQueryRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadVariablesQueryRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadVariablesQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadVariablesQueryRequest):ReadVariablesQueryRequest {
  return (obj || new ReadVariablesQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadVariablesQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadVariablesQueryRequest):ReadVariablesQueryRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadVariablesQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * An array of IDs which serves as a filter: Only those variables with the given IDs shall be returned by the provider.
 * When no IDs are given, we expect the provider to return all of its variables in the response.
 */
ids(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

idsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

idsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startReadVariablesQueryRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addIds(builder:flatbuffers.Builder, idsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idsOffset, 0);
}

static createIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endReadVariablesQueryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishReadVariablesQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadVariablesQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadVariablesQueryRequest(builder:flatbuffers.Builder, idsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReadVariablesQueryRequest.startReadVariablesQueryRequest(builder);
  ReadVariablesQueryRequest.addIds(builder, idsOffset);
  return ReadVariablesQueryRequest.endReadVariablesQueryRequest(builder);
}

unpack(): ReadVariablesQueryRequestT {
  return new ReadVariablesQueryRequestT(
    this.bb!.createScalarList<number>(this.ids.bind(this), this.idsLength())
  );
}


unpackTo(_o: ReadVariablesQueryRequestT): void {
  _o.ids = this.bb!.createScalarList<number>(this.ids.bind(this), this.idsLength());
}
}

export class ReadVariablesQueryRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public ids: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const ids = ReadVariablesQueryRequest.createIdsVector(builder, this.ids);

  return ReadVariablesQueryRequest.createReadVariablesQueryRequest(builder,
    ids
  );
}
}
