// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A query request that requests a list of providers.
 */
export class ReadProvidersQueryRequest implements flatbuffers.IUnpackableObject<ReadProvidersQueryRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadProvidersQueryRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadProvidersQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadProvidersQueryRequest):ReadProvidersQueryRequest {
  return (obj || new ReadProvidersQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadProvidersQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadProvidersQueryRequest):ReadProvidersQueryRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadProvidersQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startReadProvidersQueryRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endReadProvidersQueryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishReadProvidersQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadProvidersQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadProvidersQueryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  ReadProvidersQueryRequest.startReadProvidersQueryRequest(builder);
  return ReadProvidersQueryRequest.endReadProvidersQueryRequest(builder);
}

unpack(): ReadProvidersQueryRequestT {
  return new ReadProvidersQueryRequestT();
}


unpackTo(_o: ReadProvidersQueryRequestT): void {}
}

export class ReadProvidersQueryRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ReadProvidersQueryRequest.createReadProvidersQueryRequest(builder);
}
}
