// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A query request that requests a provider's definition.
 */
export class ReadProviderDefinitionQueryRequest implements flatbuffers.IUnpackableObject<ReadProviderDefinitionQueryRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadProviderDefinitionQueryRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadProviderDefinitionQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadProviderDefinitionQueryRequest):ReadProviderDefinitionQueryRequest {
  return (obj || new ReadProviderDefinitionQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadProviderDefinitionQueryRequest(bb:flatbuffers.ByteBuffer, obj?:ReadProviderDefinitionQueryRequest):ReadProviderDefinitionQueryRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadProviderDefinitionQueryRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startReadProviderDefinitionQueryRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endReadProviderDefinitionQueryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishReadProviderDefinitionQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadProviderDefinitionQueryRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadProviderDefinitionQueryRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  ReadProviderDefinitionQueryRequest.startReadProviderDefinitionQueryRequest(builder);
  return ReadProviderDefinitionQueryRequest.endReadProviderDefinitionQueryRequest(builder);
}

unpack(): ReadProviderDefinitionQueryRequestT {
  return new ReadProviderDefinitionQueryRequestT();
}


unpackTo(_o: ReadProviderDefinitionQueryRequestT): void {}
}

export class ReadProviderDefinitionQueryRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ReadProviderDefinitionQueryRequest.createReadProviderDefinitionQueryRequest(builder);
}
}
