// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProviderDefinition, ProviderDefinitionT } from '../../../weidmueller/ucontrol/hub/provider-definition.js';


/**
 * A query Response that returns a requested provider's definition.
 */
export class ReadProviderDefinitionQueryResponse implements flatbuffers.IUnpackableObject<ReadProviderDefinitionQueryResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadProviderDefinitionQueryResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadProviderDefinitionQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadProviderDefinitionQueryResponse):ReadProviderDefinitionQueryResponse {
  return (obj || new ReadProviderDefinitionQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadProviderDefinitionQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadProviderDefinitionQueryResponse):ReadProviderDefinitionQueryResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadProviderDefinitionQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A provider's definition that has been requested.
 */
providerDefinition(obj?:ProviderDefinition):ProviderDefinition|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ProviderDefinition()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startReadProviderDefinitionQueryResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProviderDefinition(builder:flatbuffers.Builder, providerDefinitionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, providerDefinitionOffset, 0);
}

static endReadProviderDefinitionQueryResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishReadProviderDefinitionQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadProviderDefinitionQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadProviderDefinitionQueryResponse(builder:flatbuffers.Builder, providerDefinitionOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReadProviderDefinitionQueryResponse.startReadProviderDefinitionQueryResponse(builder);
  ReadProviderDefinitionQueryResponse.addProviderDefinition(builder, providerDefinitionOffset);
  return ReadProviderDefinitionQueryResponse.endReadProviderDefinitionQueryResponse(builder);
}

unpack(): ReadProviderDefinitionQueryResponseT {
  return new ReadProviderDefinitionQueryResponseT(
    (this.providerDefinition() !== null ? this.providerDefinition()!.unpack() : null)
  );
}


unpackTo(_o: ReadProviderDefinitionQueryResponseT): void {
  _o.providerDefinition = (this.providerDefinition() !== null ? this.providerDefinition()!.unpack() : null);
}
}

export class ReadProviderDefinitionQueryResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public providerDefinition: ProviderDefinitionT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const providerDefinition = (this.providerDefinition !== null ? this.providerDefinition!.pack(builder) : 0);

  return ReadProviderDefinitionQueryResponse.createReadProviderDefinitionQueryResponse(builder,
    providerDefinition
  );
}
}
