// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProviderList, ProviderListT } from '../../../weidmueller/ucontrol/hub/provider-list.js';


/**
 * A query response that returns a requested list of providers.
 */
export class ReadProvidersQueryResponse implements flatbuffers.IUnpackableObject<ReadProvidersQueryResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReadProvidersQueryResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReadProvidersQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadProvidersQueryResponse):ReadProvidersQueryResponse {
  return (obj || new ReadProvidersQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReadProvidersQueryResponse(bb:flatbuffers.ByteBuffer, obj?:ReadProvidersQueryResponse):ReadProvidersQueryResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReadProvidersQueryResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of providers that have been requested.
 */
providers(obj?:ProviderList):ProviderList|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ProviderList()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startReadProvidersQueryResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProviders(builder:flatbuffers.Builder, providersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, providersOffset, 0);
}

static endReadProvidersQueryResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // providers
  return offset;
}

static finishReadProvidersQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedReadProvidersQueryResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createReadProvidersQueryResponse(builder:flatbuffers.Builder, providersOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReadProvidersQueryResponse.startReadProvidersQueryResponse(builder);
  ReadProvidersQueryResponse.addProviders(builder, providersOffset);
  return ReadProvidersQueryResponse.endReadProvidersQueryResponse(builder);
}

unpack(): ReadProvidersQueryResponseT {
  return new ReadProvidersQueryResponseT(
    (this.providers() !== null ? this.providers()!.unpack() : null)
  );
}


unpackTo(_o: ReadProvidersQueryResponseT): void {
  _o.providers = (this.providers() !== null ? this.providers()!.unpack() : null);
}
}

export class ReadProvidersQueryResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public providers: ProviderListT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const providers = (this.providers !== null ? this.providers!.pack(builder) : 0);

  return ReadProvidersQueryResponse.createReadProvidersQueryResponse(builder,
    providers
  );
}
}
