// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * A state of a service.
 *
 * The state names are based on
 * [the status names of the systemd services](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#is-system-running).
 */
export enum State {
  UNSPECIFIED = 0,
  RUNNING = 1,
  STOPPING = 2
}
