// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { State } from '../../../weidmueller/ucontrol/hub/state.js';


/**
 * An event that describes a state that has just changed.
 */
export class StateChangedEvent implements flatbuffers.IUnpackableObject<StateChangedEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StateChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStateChangedEvent(bb:flatbuffers.ByteBuffer, obj?:StateChangedEvent):StateChangedEvent {
  return (obj || new StateChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStateChangedEvent(bb:flatbuffers.ByteBuffer, obj?:StateChangedEvent):StateChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StateChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A state that has just been changed.
 */
state():State {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : State.UNSPECIFIED;
}

static startStateChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addState(builder:flatbuffers.Builder, state:State) {
  builder.addFieldInt8(0, state, State.UNSPECIFIED);
}

static endStateChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishStateChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedStateChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createStateChangedEvent(builder:flatbuffers.Builder, state:State):flatbuffers.Offset {
  StateChangedEvent.startStateChangedEvent(builder);
  StateChangedEvent.addState(builder, state);
  return StateChangedEvent.endStateChangedEvent(builder);
}

unpack(): StateChangedEventT {
  return new StateChangedEventT(
    this.state()
  );
}


unpackTo(_o: StateChangedEventT): void {
  _o.state = this.state();
}
}

export class StateChangedEventT implements flatbuffers.IGeneratedObject {
constructor(
  public state: State = State.UNSPECIFIED
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StateChangedEvent.createStateChangedEvent(builder,
    this.state
  );
}
}
