// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A timestamp measured by the number of nanoseconds that have elapsed
 * since 00:00:00 UTC on 1 January 1970, which is referred to as the Unix
 * epoch, without adjustments made due to leap seconds.
 *
 * Based on google protobuf timestamp definition: <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto>
 */
export class Timestamp implements flatbuffers.IUnpackableObject<TimestampT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Timestamp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

/**
 * Represents seconds of UTC time since Unix epoch
 * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
 * 9999-12-31T23:59:59Z inclusive.
 */
seconds():bigint {
  return this.bb!.readInt64(this.bb_pos);
}

/**
 * Non-negative fractions of a second at nanosecond resolution. Negative
 * second values with fractions must still have non-negative nanos values
 * that count forward in time. Must be from 0 to 999,999,999
 * inclusive.
 */
nanos():number {
  return this.bb!.readInt32(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createTimestamp(builder:flatbuffers.Builder, seconds: bigint, nanos: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.pad(4);
  builder.writeInt32(nanos);
  builder.writeInt64(BigInt(seconds ?? 0));
  return builder.offset();
}


unpack(): TimestampT {
  return new TimestampT(
    this.seconds(),
    this.nanos()
  );
}


unpackTo(_o: TimestampT): void {
  _o.seconds = this.seconds();
  _o.nanos = this.nanos();
}
}

export class TimestampT implements flatbuffers.IGeneratedObject {
constructor(
  public seconds: bigint = BigInt('0'),
  public nanos: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Timestamp.createTimestamp(builder,
    this.seconds,
    this.nanos
  );
}
}
