// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Uuid implements flatbuffers.IUnpackableObject<UuidT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Uuid {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

upper():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

lower():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createUuid(builder:flatbuffers.Builder, upper: bigint, lower: bigint):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(BigInt(lower ?? 0));
  builder.writeInt64(BigInt(upper ?? 0));
  return builder.offset();
}


unpack(): UuidT {
  return new UuidT(
    this.upper(),
    this.lower()
  );
}


unpackTo(_o: UuidT): void {
  _o.upper = this.upper();
  _o.lower = this.lower();
}
}

export class UuidT implements flatbuffers.IGeneratedObject {
constructor(
  public upper: bigint = BigInt('0'),
  public lower: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Uuid.createUuid(builder,
    this.upper,
    this.lower
  );
}
}
