// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A 64-bit, signed integer value of a variable.
 */
export class VariableValueInt64 implements flatbuffers.IUnpackableObject<VariableValueInt64T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueInt64 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueInt64(bb:flatbuffers.ByteBuffer, obj?:VariableValueInt64):VariableValueInt64 {
  return (obj || new VariableValueInt64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueInt64(bb:flatbuffers.ByteBuffer, obj?:VariableValueInt64):VariableValueInt64 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueInt64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startVariableValueInt64(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:bigint) {
  builder.addFieldInt64(0, value, BigInt('0'));
}

static endVariableValueInt64(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueInt64(builder:flatbuffers.Builder, value:bigint):flatbuffers.Offset {
  VariableValueInt64.startVariableValueInt64(builder);
  VariableValueInt64.addValue(builder, value);
  return VariableValueInt64.endVariableValueInt64(builder);
}

unpack(): VariableValueInt64T {
  return new VariableValueInt64T(
    this.value()
  );
}


unpackTo(_o: VariableValueInt64T): void {
  _o.value = this.value();
}
}

export class VariableValueInt64T implements flatbuffers.IGeneratedObject {
constructor(
  public value: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VariableValueInt64.createVariableValueInt64(builder,
    this.value
  );
}
}
