// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { VariableAccessType } from '../../../weidmueller/ucontrol/hub/variable-access-type.js';
import { VariableDataType } from '../../../weidmueller/ucontrol/hub/variable-data-type.js';


/**
 * The definition of a variable.
 */
export class VariableDefinition implements flatbuffers.IUnpackableObject<VariableDefinitionT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableDefinition {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableDefinition(bb:flatbuffers.ByteBuffer, obj?:VariableDefinition):VariableDefinition {
  return (obj || new VariableDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableDefinition(bb:flatbuffers.ByteBuffer, obj?:VariableDefinition):VariableDefinition {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableDefinition()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The provider's unique key of the variable.
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * The unique ID of the variable. It is only unique via one provider.
 */
id():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The data type of the variable.
 */
dataType():VariableDataType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : VariableDataType.UNSPECIFIED;
}

/**
 * The access type of the variable.
 */
accessType():VariableAccessType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : VariableAccessType.UNSPECIFIED;
}

/**
 * Marker to indicate whether the variable is experimental.
 *
 * Experimental means that the variable is not stable/reliable and it is hidden in the user interface.
 */
experimental():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startVariableDefinition(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
}

static addDataType(builder:flatbuffers.Builder, dataType:VariableDataType) {
  builder.addFieldInt8(2, dataType, VariableDataType.UNSPECIFIED);
}

static addAccessType(builder:flatbuffers.Builder, accessType:VariableAccessType) {
  builder.addFieldInt8(3, accessType, VariableAccessType.UNSPECIFIED);
}

static addExperimental(builder:flatbuffers.Builder, experimental:boolean) {
  builder.addFieldInt8(4, +experimental, +false);
}

static endVariableDefinition(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  return offset;
}

static createVariableDefinition(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, id:number, dataType:VariableDataType, accessType:VariableAccessType, experimental:boolean):flatbuffers.Offset {
  VariableDefinition.startVariableDefinition(builder);
  VariableDefinition.addKey(builder, keyOffset);
  VariableDefinition.addId(builder, id);
  VariableDefinition.addDataType(builder, dataType);
  VariableDefinition.addAccessType(builder, accessType);
  VariableDefinition.addExperimental(builder, experimental);
  return VariableDefinition.endVariableDefinition(builder);
}

unpack(): VariableDefinitionT {
  return new VariableDefinitionT(
    this.key(),
    this.id(),
    this.dataType(),
    this.accessType(),
    this.experimental()
  );
}


unpackTo(_o: VariableDefinitionT): void {
  _o.key = this.key();
  _o.id = this.id();
  _o.dataType = this.dataType();
  _o.accessType = this.accessType();
  _o.experimental = this.experimental();
}
}

export class VariableDefinitionT implements flatbuffers.IGeneratedObject {
constructor(
  public key: string|Uint8Array|null = null,
  public id: number = 0,
  public dataType: VariableDataType = VariableDataType.UNSPECIFIED,
  public accessType: VariableAccessType = VariableAccessType.UNSPECIFIED,
  public experimental: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);

  return VariableDefinition.createVariableDefinition(builder,
    key,
    this.id,
    this.dataType,
    this.accessType,
    this.experimental
  );
}
}
