// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * The access type of a variable.
 */
export enum VariableAccessType {
  UNSPECIFIED = 0,

  /**
   * Consumers can only read the variable.
   */
  READ_ONLY = 1,

  /**
   * Consumers can read and write the variable.
   */
  READ_WRITE = 2
}
