// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * The data type of a variable.
 */
export enum VariableDataType {
  UNSPECIFIED = 0,
  BOOLEAN = 1,
  DURATION = 2,
  FLOAT64 = 3,
  INT64 = 4,
  STRING = 5,
  TIMESTAMP = 6
}
