// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Timestamp, TimestampT } from '../../../weidmueller/ucontrol/hub/timestamp.js';
import { Variable, VariableT } from '../../../weidmueller/ucontrol/hub/variable.js';


/**
 * A list of a provider's variables that match the provider's definition.
 */
export class VariableList implements flatbuffers.IUnpackableObject<VariableListT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableList(bb:flatbuffers.ByteBuffer, obj?:VariableList):VariableList {
  return (obj || new VariableList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableList(bb:flatbuffers.ByteBuffer, obj?:VariableList):VariableList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * The fingerprint of the associated provider's definition.
 */
providerDefinitionFingerprint():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * The timestamp for all changed variables. The base timestamp is the
 * fallback if no explicit was specified for the variable.
 *
 * Only set by the provider!
 * Consumers can set it to 0s and 0ns. This value is ignored by the
 * provider in a write command.
 */
baseTimestamp(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Timestamp()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The items of the provider's variable list.
 */
items(index: number, obj?:Variable):Variable|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Variable()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startVariableList(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addProviderDefinitionFingerprint(builder:flatbuffers.Builder, providerDefinitionFingerprint:bigint) {
  builder.addFieldInt64(0, providerDefinitionFingerprint, BigInt('0'));
}

static addBaseTimestamp(builder:flatbuffers.Builder, baseTimestampOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, baseTimestampOffset, 0);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVariableList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // base_timestamp
  return offset;
}


unpack(): VariableListT {
  return new VariableListT(
    this.providerDefinitionFingerprint(),
    (this.baseTimestamp() !== null ? this.baseTimestamp()!.unpack() : null),
    this.bb!.createObjList<Variable, VariableT>(this.items.bind(this), this.itemsLength())
  );
}


unpackTo(_o: VariableListT): void {
  _o.providerDefinitionFingerprint = this.providerDefinitionFingerprint();
  _o.baseTimestamp = (this.baseTimestamp() !== null ? this.baseTimestamp()!.unpack() : null);
  _o.items = this.bb!.createObjList<Variable, VariableT>(this.items.bind(this), this.itemsLength());
}
}

export class VariableListT implements flatbuffers.IGeneratedObject {
constructor(
  public providerDefinitionFingerprint: bigint = BigInt('0'),
  public baseTimestamp: TimestampT|null = null,
  public items: (VariableT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const items = VariableList.createItemsVector(builder, builder.createObjectOffsetList(this.items));

  VariableList.startVariableList(builder);
  VariableList.addProviderDefinitionFingerprint(builder, this.providerDefinitionFingerprint);
  VariableList.addBaseTimestamp(builder, (this.baseTimestamp !== null ? this.baseTimestamp!.pack(builder) : 0));
  VariableList.addItems(builder, items);

  return VariableList.endVariableList(builder);
}
}
