// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Timestamp, TimestampT } from '../../../weidmueller/ucontrol/hub/timestamp.js';
import { VariableQuality } from '../../../weidmueller/ucontrol/hub/variable-quality.js';
import { VariableValue, unionToVariableValue, unionListToVariableValue } from '../../../weidmueller/ucontrol/hub/variable-value.js';
import { VariableValueBoolean, VariableValueBooleanT } from '../../../weidmueller/ucontrol/hub/variable-value-boolean.js';
import { VariableValueDuration, VariableValueDurationT } from '../../../weidmueller/ucontrol/hub/variable-value-duration.js';
import { VariableValueFloat64, VariableValueFloat64T } from '../../../weidmueller/ucontrol/hub/variable-value-float64.js';
import { VariableValueInt64, VariableValueInt64T } from '../../../weidmueller/ucontrol/hub/variable-value-int64.js';
import { VariableValueString, VariableValueStringT } from '../../../weidmueller/ucontrol/hub/variable-value-string.js';
import { VariableValueTimestamp, VariableValueTimestampT } from '../../../weidmueller/ucontrol/hub/variable-value-timestamp.js';


/**
 * A variable associated with the provider's definition.
 */
export class Variable implements flatbuffers.IUnpackableObject<VariableT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Variable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariable(bb:flatbuffers.ByteBuffer, obj?:Variable):Variable {
  return (obj || new Variable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariable(bb:flatbuffers.ByteBuffer, obj?:Variable):Variable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Variable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

valueType():VariableValue {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VariableValue.NONE;
}

/**
 * The value of the variable.
 */
value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

/**
 * The ID of the variable associated with the provider's definition.
 */
id():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * The individual timestamp of the variable.
 *
 * Only set by the provider!
 * Consumers can left this empty. This value is ignored by the provider in
 * a write command.
 */
timestamp(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Timestamp()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * The quality of the variable.
 *
 * Only set by the provider!
 * Consumers can set it to BAD. This value is ignored by the provider
 * in a write command.
 */
quality():VariableQuality {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VariableQuality.BAD;
}

static startVariable(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addValueType(builder:flatbuffers.Builder, valueType:VariableValue) {
  builder.addFieldInt8(0, valueType, VariableValue.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(2, id, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestampOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, timestampOffset, 0);
}

static addQuality(builder:flatbuffers.Builder, quality:VariableQuality) {
  builder.addFieldInt8(4, quality, VariableQuality.BAD);
}

static endVariable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // value
  return offset;
}


unpack(): VariableT {
  return new VariableT(
    this.valueType(),
    (() => {
      const temp = unionToVariableValue(this.valueType(), this.value.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })(),
    this.id(),
    (this.timestamp() !== null ? this.timestamp()!.unpack() : null),
    this.quality()
  );
}


unpackTo(_o: VariableT): void {
  _o.valueType = this.valueType();
  _o.value = (() => {
      const temp = unionToVariableValue(this.valueType(), this.value.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
  _o.id = this.id();
  _o.timestamp = (this.timestamp() !== null ? this.timestamp()!.unpack() : null);
  _o.quality = this.quality();
}
}

export class VariableT implements flatbuffers.IGeneratedObject {
constructor(
  public valueType: VariableValue = VariableValue.NONE,
  public value: VariableValueBooleanT|VariableValueDurationT|VariableValueFloat64T|VariableValueInt64T|VariableValueStringT|VariableValueTimestampT|null = null,
  public id: number = 0,
  public timestamp: TimestampT|null = null,
  public quality: VariableQuality = VariableQuality.BAD
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = builder.createObjectOffset(this.value);

  Variable.startVariable(builder);
  Variable.addValueType(builder, this.valueType);
  Variable.addValue(builder, value);
  Variable.addId(builder, this.id);
  Variable.addTimestamp(builder, (this.timestamp !== null ? this.timestamp!.pack(builder) : 0));
  Variable.addQuality(builder, this.quality);

  return Variable.endVariable(builder);
}
}
