// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A string value of a variable.
 */
export class VariableValueString implements flatbuffers.IUnpackableObject<VariableValueStringT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueString {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueString(bb:flatbuffers.ByteBuffer, obj?:VariableValueString):VariableValueString {
  return (obj || new VariableValueString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueString(bb:flatbuffers.ByteBuffer, obj?:VariableValueString):VariableValueString {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startVariableValueString(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static endVariableValueString(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueString(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  VariableValueString.startVariableValueString(builder);
  VariableValueString.addValue(builder, valueOffset);
  return VariableValueString.endVariableValueString(builder);
}

unpack(): VariableValueStringT {
  return new VariableValueStringT(
    this.value()
  );
}


unpackTo(_o: VariableValueStringT): void {
  _o.value = this.value();
}
}

export class VariableValueStringT implements flatbuffers.IGeneratedObject {
constructor(
  public value: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = (this.value !== null ? builder.createString(this.value!) : 0);

  return VariableValueString.createVariableValueString(builder,
    value
  );
}
}
