// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Timestamp, TimestampT } from '../../../weidmueller/ucontrol/hub/timestamp.js';


/**
 * A date and time value of a variable.
 */
export class VariableValueTimestamp implements flatbuffers.IUnpackableObject<VariableValueTimestampT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueTimestamp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueTimestamp(bb:flatbuffers.ByteBuffer, obj?:VariableValueTimestamp):VariableValueTimestamp {
  return (obj || new VariableValueTimestamp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueTimestamp(bb:flatbuffers.ByteBuffer, obj?:VariableValueTimestamp):VariableValueTimestamp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueTimestamp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:Timestamp):Timestamp|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Timestamp()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startVariableValueTimestamp(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, valueOffset, 0);
}

static endVariableValueTimestamp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueTimestamp(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  VariableValueTimestamp.startVariableValueTimestamp(builder);
  VariableValueTimestamp.addValue(builder, valueOffset);
  return VariableValueTimestamp.endVariableValueTimestamp(builder);
}

unpack(): VariableValueTimestampT {
  return new VariableValueTimestampT(
    (this.value() !== null ? this.value()!.unpack() : null)
  );
}


unpackTo(_o: VariableValueTimestampT): void {
  _o.value = (this.value() !== null ? this.value()!.unpack() : null);
}
}

export class VariableValueTimestampT implements flatbuffers.IGeneratedObject {
constructor(
  public value: TimestampT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VariableValueTimestamp.createVariableValueTimestamp(builder,
    (this.value !== null ? this.value!.pack(builder) : 0)
  );
}
}
