// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { VariableList, VariableListT } from '../../../weidmueller/ucontrol/hub/variable-list.js';


/**
 * An event that describes a provider's list of variables that have just
 * changed.
 */
export class VariablesChangedEvent implements flatbuffers.IUnpackableObject<VariablesChangedEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariablesChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariablesChangedEvent(bb:flatbuffers.ByteBuffer, obj?:VariablesChangedEvent):VariablesChangedEvent {
  return (obj || new VariablesChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariablesChangedEvent(bb:flatbuffers.ByteBuffer, obj?:VariablesChangedEvent):VariablesChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariablesChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of variables that have just been changed.
 * Only contains changed variables!
 */
changedVariables(obj?:VariableList):VariableList|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VariableList()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startVariablesChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addChangedVariables(builder:flatbuffers.Builder, changedVariablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, changedVariablesOffset, 0);
}

static endVariablesChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // changed_variables
  return offset;
}

static finishVariablesChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedVariablesChangedEventBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createVariablesChangedEvent(builder:flatbuffers.Builder, changedVariablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  VariablesChangedEvent.startVariablesChangedEvent(builder);
  VariablesChangedEvent.addChangedVariables(builder, changedVariablesOffset);
  return VariablesChangedEvent.endVariablesChangedEvent(builder);
}

unpack(): VariablesChangedEventT {
  return new VariablesChangedEventT(
    (this.changedVariables() !== null ? this.changedVariables()!.unpack() : null)
  );
}


unpackTo(_o: VariablesChangedEventT): void {
  _o.changedVariables = (this.changedVariables() !== null ? this.changedVariables()!.unpack() : null);
}
}

export class VariablesChangedEventT implements flatbuffers.IGeneratedObject {
constructor(
  public changedVariables: VariableListT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const changedVariables = (this.changedVariables !== null ? this.changedVariables!.pack(builder) : 0);

  return VariablesChangedEvent.createVariablesChangedEvent(builder,
    changedVariables
  );
}
}
