// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Duration, DurationT } from '../../../weidmueller/ucontrol/hub/duration.js';


/**
 * A duration value of a variable.
 */
export class VariableValueDuration implements flatbuffers.IUnpackableObject<VariableValueDurationT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueDuration {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueDuration(bb:flatbuffers.ByteBuffer, obj?:VariableValueDuration):VariableValueDuration {
  return (obj || new VariableValueDuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueDuration(bb:flatbuffers.ByteBuffer, obj?:VariableValueDuration):VariableValueDuration {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueDuration()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:Duration):Duration|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Duration()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startVariableValueDuration(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, valueOffset, 0);
}

static endVariableValueDuration(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueDuration(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  VariableValueDuration.startVariableValueDuration(builder);
  VariableValueDuration.addValue(builder, valueOffset);
  return VariableValueDuration.endVariableValueDuration(builder);
}

unpack(): VariableValueDurationT {
  return new VariableValueDurationT(
    (this.value() !== null ? this.value()!.unpack() : null)
  );
}


unpackTo(_o: VariableValueDurationT): void {
  _o.value = (this.value() !== null ? this.value()!.unpack() : null);
}
}

export class VariableValueDurationT implements flatbuffers.IGeneratedObject {
constructor(
  public value: DurationT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VariableValueDuration.createVariableValueDuration(builder,
    (this.value !== null ? this.value!.pack(builder) : 0)
  );
}
}
