// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { VariableValueBoolean, VariableValueBooleanT } from '../../../weidmueller/ucontrol/hub/variable-value-boolean.js';
import { VariableValueDuration, VariableValueDurationT } from '../../../weidmueller/ucontrol/hub/variable-value-duration.js';
import { VariableValueFloat64, VariableValueFloat64T } from '../../../weidmueller/ucontrol/hub/variable-value-float64.js';
import { VariableValueInt64, VariableValueInt64T } from '../../../weidmueller/ucontrol/hub/variable-value-int64.js';
import { VariableValueString, VariableValueStringT } from '../../../weidmueller/ucontrol/hub/variable-value-string.js';
import { VariableValueTimestamp, VariableValueTimestampT } from '../../../weidmueller/ucontrol/hub/variable-value-timestamp.js';


/**
 * The value of a variable.
 */
export enum VariableValue {
  NONE = 0,
  Boolean = 1,
  Duration = 2,
  Float64 = 3,
  Int64 = 4,
  String = 5,
  Timestamp = 6
}

export function unionToVariableValue(
  type: VariableValue,
  accessor: (obj:VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp) => VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp|null
): VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp|null {
  switch(VariableValue[type]) {
    case 'NONE': return null; 
    case 'Boolean': return accessor(new VariableValueBoolean())! as VariableValueBoolean;
    case 'Duration': return accessor(new VariableValueDuration())! as VariableValueDuration;
    case 'Float64': return accessor(new VariableValueFloat64())! as VariableValueFloat64;
    case 'Int64': return accessor(new VariableValueInt64())! as VariableValueInt64;
    case 'String': return accessor(new VariableValueString())! as VariableValueString;
    case 'Timestamp': return accessor(new VariableValueTimestamp())! as VariableValueTimestamp;
    default: return null;
  }
}

export function unionListToVariableValue(
  type: VariableValue, 
  accessor: (index: number, obj:VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp) => VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp|null, 
  index: number
): VariableValueBoolean|VariableValueDuration|VariableValueFloat64|VariableValueInt64|VariableValueString|VariableValueTimestamp|null {
  switch(VariableValue[type]) {
    case 'NONE': return null; 
    case 'Boolean': return accessor(index, new VariableValueBoolean())! as VariableValueBoolean;
    case 'Duration': return accessor(index, new VariableValueDuration())! as VariableValueDuration;
    case 'Float64': return accessor(index, new VariableValueFloat64())! as VariableValueFloat64;
    case 'Int64': return accessor(index, new VariableValueInt64())! as VariableValueInt64;
    case 'String': return accessor(index, new VariableValueString())! as VariableValueString;
    case 'Timestamp': return accessor(index, new VariableValueTimestamp())! as VariableValueTimestamp;
    default: return null;
  }
}
