// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A boolean value of a variable.
 */
export class VariableValueBoolean implements flatbuffers.IUnpackableObject<VariableValueBooleanT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueBoolean {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueBoolean(bb:flatbuffers.ByteBuffer, obj?:VariableValueBoolean):VariableValueBoolean {
  return (obj || new VariableValueBoolean()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueBoolean(bb:flatbuffers.ByteBuffer, obj?:VariableValueBoolean):VariableValueBoolean {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueBoolean()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startVariableValueBoolean(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:boolean) {
  builder.addFieldInt8(0, +value, +false);
}

static endVariableValueBoolean(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueBoolean(builder:flatbuffers.Builder, value:boolean):flatbuffers.Offset {
  VariableValueBoolean.startVariableValueBoolean(builder);
  VariableValueBoolean.addValue(builder, value);
  return VariableValueBoolean.endVariableValueBoolean(builder);
}

unpack(): VariableValueBooleanT {
  return new VariableValueBooleanT(
    this.value()
  );
}


unpackTo(_o: VariableValueBooleanT): void {
  _o.value = this.value();
}
}

export class VariableValueBooleanT implements flatbuffers.IGeneratedObject {
constructor(
  public value: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VariableValueBoolean.createVariableValueBoolean(builder,
    this.value
  );
}
}
