// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * A precision floating-point value of a variable.
 */
export class VariableValueFloat64 implements flatbuffers.IUnpackableObject<VariableValueFloat64T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VariableValueFloat64 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVariableValueFloat64(bb:flatbuffers.ByteBuffer, obj?:VariableValueFloat64):VariableValueFloat64 {
  return (obj || new VariableValueFloat64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVariableValueFloat64(bb:flatbuffers.ByteBuffer, obj?:VariableValueFloat64):VariableValueFloat64 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VariableValueFloat64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startVariableValueFloat64(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat64(0, value, 0.0);
}

static endVariableValueFloat64(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVariableValueFloat64(builder:flatbuffers.Builder, value:number):flatbuffers.Offset {
  VariableValueFloat64.startVariableValueFloat64(builder);
  VariableValueFloat64.addValue(builder, value);
  return VariableValueFloat64.endVariableValueFloat64(builder);
}

unpack(): VariableValueFloat64T {
  return new VariableValueFloat64T(
    this.value()
  );
}


unpackTo(_o: VariableValueFloat64T): void {
  _o.value = this.value();
}
}

export class VariableValueFloat64T implements flatbuffers.IGeneratedObject {
constructor(
  public value: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VariableValueFloat64.createVariableValueFloat64(builder,
    this.value
  );
}
}
