// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { VariableList, VariableListT } from '../../../weidmueller/ucontrol/hub/variable-list.js';


/**
 * A command writing a list of provider variables.
 */
export class WriteVariablesCommand implements flatbuffers.IUnpackableObject<WriteVariablesCommandT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WriteVariablesCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWriteVariablesCommand(bb:flatbuffers.ByteBuffer, obj?:WriteVariablesCommand):WriteVariablesCommand {
  return (obj || new WriteVariablesCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWriteVariablesCommand(bb:flatbuffers.ByteBuffer, obj?:WriteVariablesCommand):WriteVariablesCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WriteVariablesCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * A list of variables that have to be written.
 */
variables(obj?:VariableList):VariableList|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VariableList()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startWriteVariablesCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addVariables(builder:flatbuffers.Builder, variablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, variablesOffset, 0);
}

static endWriteVariablesCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // variables
  return offset;
}

static finishWriteVariablesCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedWriteVariablesCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createWriteVariablesCommand(builder:flatbuffers.Builder, variablesOffset:flatbuffers.Offset):flatbuffers.Offset {
  WriteVariablesCommand.startWriteVariablesCommand(builder);
  WriteVariablesCommand.addVariables(builder, variablesOffset);
  return WriteVariablesCommand.endWriteVariablesCommand(builder);
}

unpack(): WriteVariablesCommandT {
  return new WriteVariablesCommandT(
    (this.variables() !== null ? this.variables()!.unpack() : null)
  );
}


unpackTo(_o: WriteVariablesCommandT): void {
  _o.variables = (this.variables() !== null ? this.variables()!.unpack() : null);
}
}

export class WriteVariablesCommandT implements flatbuffers.IGeneratedObject {
constructor(
  public variables: VariableListT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const variables = (this.variables !== null ? this.variables!.pack(builder) : 0);

  return WriteVariablesCommand.createWriteVariablesCommand(builder,
    variables
  );
}
}
